### ISSUE TITLE
Set up ESLint

### ISSUE THREAD

**Issue by Simply007** [Kentico/kentico.github.io#12]
### Motivation

Project code if full of inline comments disabling of the eslint. 
i.e.:
`// eslint-disable-next-line no-undef`

### Proposed solution

Set up es-lint - ideally two different configuration one for [frontend](https://github.com/Kentico/kentico.github.io/tree/source/src) and one for [Azure functions](https://github.com/Kentico/kentico.github.io/tree/source/src/azureFunctions)

### Additional context

* https://eslint.org/docs/user-guide/configuring
* https://github.com/Kentico/cloud-sample-app-react/issues/84
* https://github.com/Kentico/cloud-sample-app-vue/issues/6
* https://github.com/Kentico/cloud-sample-app-react/issues/84

**Comment by thanhcng** [comment]
Can I work on this?

**Comment by petrsvihlik** [comment]
thanks for the PR @thanhcng !
