### ISSUE TITLE
Refactor CSS definition

### ISSUE THREAD

**Issue by Simply007** [Kentico/kentico.github.io#14]
### Motivation

Make the CSS definition more organized and scalable.

The current state is that most of the CSS is stored in [index.scss](https://github.com/Kentico/kentico.github.io/blob/source/src/pages/index.scss) and the rest is defined inline.

### Proposed solution

Extract into separate files:
* Variable definitions
* Mixins 
* Global site (page) styles 
* Section specific styles and rename the class first, second,... to more semantic ones

**Comment by dacdao1** [comment]
Hi, I want to know if I could work on this issue for you if it hasn't been started yet. Thank you.

**Comment by Simply007** [comment]
Hello @dacdao1,
I've just sent you an invitation to the project. If you accept it, I'll be able to assign the issue to you.

All the issues without assignee and marked with `help wanted` label are ready to be taken.

**Comment by dacdao1** [comment]
Hi, I just accepted the invitation to the project. Is there anything else I need to do before taking in this issue? Thank you.

**Comment by Simply007** [comment]
Great @dacdao1,

you are ready to start on the issue.
To run the site locally, follow [Quick start section on the source branch](https://github.com/Kentico/kentico.github.io/tree/source#-quick-start).

The main requirement for the refactoring is to split the section styles to separate files, separate mixins and variable to the separate file.

If you have any question, feel free to ask!

**Comment by dacdao1** [comment]
Would you look over the files and changes that I added to the source branch? I know that I didn't organize the folders and layout the way you would like, but at least everything is in its files and folders. Please let me know if I completed the task the way you wanted. Also, I saw that within the components folder with those different Javascript files, there are also CSS styling to some of those classes. Would you like me to take those styling out and add them to the specific scss files? Thank you for letting me be a part of this project.

**Comment by Simply007** [comment]
Let's discuss in #30 pull request.

I have already added some comments. 
Thanks, @dacdao1!

**Comment by dacdao1** [comment]
Please let me know if I committed to the right branch, thank you for helping me so far @Simply007

**Comment by Simply007** [comment]
Fixes in #30

**Comment by Simply007** [comment]
Fixes in #30
