### ISSUE TITLE
Adjust PropTypes for Kentico Cloud Fields.

### ISSUE THREAD

**Issue by Simply007** [Kentico/kentico.github.io#6]
Create type-checking for [all Kentico Kontent Field types](https://docs.kontent.ai/reference/delivery-api#tag/Content-elements).

Type checking in react: 
https://reactjs.org/docs/typechecking-with-proptypes.html

Basically, it is required to create a set of objects that define a shape of elements in graph model provided by [gatsby-source-kentico-cloud](https://www.npmjs.com/package/gatsby-source-kentico-cloud) plugin.

Requirements:
* text - exact shape 
* rich_text - object contains propery walue which is type string
* number - exact shape
* multiple_choice - array of choices - define shape
* date_time - exact shape
* asset - array of asset (define asset type) 
* modular_content (Linked items element) - array of objecs 
* taxonomy - list of if taxomomy (+ define taxonomy shape)
*  url_slug.

**Comment by chynh** [comment]
@Simply007 
I've been tackling this issue and this is a snippet of what I have so far:
```
import PropTypes, { shape, exact, oneOf, arrayOf } from 'prop-types';

const capitalize = el => {
  return el[0].toUpperCase() + el.slice(1);
};

const kenticoCloudFieldTypes = {
  text(element) {
    return exact({
      type: oneOf(['text']),
      name: oneOf([capitalize(element)]),
      value: PropTypes.string
    });
  },

  number(element) {
    return exact({
      type: oneOf(['number']),
      name: oneOf([capitalize(element)]),
      value: PropTypes.number
    });
  },
};
export default kenticoCloudFieldTypes;
```
Just wanted to check whether this is similar to what you had in mind before going ahead.

**Comment by Simply007** [comment]
@chynh it looks really promising.

I have just one question what is the behavior of the `exact` if you not provide the property. Or how did you planned to use in the component that expects i.e. two text fields - could you provide your idea?

My initial idea was that you won't be forced to define prop types structure in every component, so you just define ti like:
```js
HeadingSection.propTypes = {
  title: KenticoCloudElements.textElement,
  subTitle: KenticoCloudElements.textElement
};
```

And if you get ne no error when the provided object contains `name`, `value` and `type` property of type string, it is fine (even if you provide just two or just one in an ideal scenario, but it is not required in the sope in this issue)).

**Comment by Simply007** [comment]
Hey @chynh - sorry for the late response.

You are correct. I wouldn't set any of the parameters required, because, when you are querying data using GraphQL, you could use projection to select only some of the properties. 

According to the prototype, I would start with the `text` element that should be simple and expect the object could have only `name`, `type`, `value` and `text` property, but non of these is required.
According to the `type` property value - it should be 'text'.

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a while since the last update here.

If we missed anything on this issue or if you want to keep it open, please re-open it.

Thanks for being a part of the Kentico community!
